### ISSUE TITLE
Couldn't find where to change the damping factor.

### ISSUE THREAD

**Issue by tomarharsh** [jerrygaoLondon/jgtextrank#1]
The original paper on TextRank by Mihalcea, R., & Tarau, P. mentions the damping factor and that it should be set to 0.85.

I couldn't really find any place to fix the damping factor in your implementation.

**Comment by jerrygaoLondon** [comment]
The damping factor is set to 0.85 by default.  It seems that no one has the motivation to tune the parameter since pagerank is invented. So, I didn't expose this setting to the API.

**Comment by tomarharsh** [comment]
Got it! Thanks!
